import {existsSync,readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {generateJson,isChatGptModelId,isOpenAiModelId} from '@ljoukov/llm';
import {z} from 'zod';
import {goalCampingInstruction,goalCampingProgress} from './web/goal-camping.js';
const envPath=new URL('.env',import.meta.url);
const local=existsSync(envPath)?parseEnv(readFileSync(envPath,'utf8')):{};
const apiKey=local.OPENAI_API_KEY || process.env.OPENAI_API_KEY;
if(apiKey)process.env.OPENAI_API_KEY=apiKey;
for(const name of ['CHATGPT_AUTH_TOKEN_PROVIDER_URL','CHATGPT_AUTH_TOKEN_PROVIDER_API_KEY','CHATGPT_AUTH_API_KEY','CHATGPT_CODEX_PROXY_URL','CHATGPT_CODEX_PROXY_API_KEY','CHATGPT_RESPONSES_WEBSOCKET_MODE'])if(local[name])process.env[name]=local[name];
export function modelForGame(){return process.env.GAMEPLAY_LLM_MODEL||local.GAMEPLAY_LLM_MODEL||'chatgpt-gpt-6-luna-fast';}
export function agentConfig(game){
 const model=modelForGame(game),subscription=isChatGptModelId(model);
 const configured=subscription?(existsSync(join(process.env.CODEX_HOME||join(homedir(),'.codex'),'auth.json'))||Boolean(process.env.CHATGPT_AUTH_TOKEN_PROVIDER_URL&&(process.env.CHATGPT_AUTH_TOKEN_PROVIDER_API_KEY||process.env.CHATGPT_AUTH_API_KEY))||Boolean(process.env.CHATGPT_CODEX_PROXY_URL&&process.env.CHATGPT_CODEX_PROXY_API_KEY)):Boolean(apiKey);
 return {model,configured,thinkingLevel:'low',transport:subscription?'ChatGPT subscription':'OpenAI API'};
}
const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyZ','KeyX','Space','KeyR'];
const prompts={
 'football-legends':`You are a Swarm QA agent testing the ORIGINAL Football Legends against its built-in bot. This is a guided exploit investigation. Hypothesis supplied by the tester: jumping into your own raised goal and camping there makes defending too easy; wait for naturally recharging super shot, then score across the field. Try to validate or falsify it using ordinary keys only. You control the human player (human:true); direction -1 defends the LEFT goal and scores at the RIGHT. World width is 800. Use a camp at x≈65–90, NOT the back edge x≈20. Left net interior x≈30–95, its floor is raised: you must JUMP left over the step at x≈105. Human starts x250 y336. ArrowLeft/Right move, ArrowUp jumps (release before a second jump), ArrowDown slides. KeyZ is super shot; KeyX normal shot. SuperPower 0 is fireball; 1 teleports. The charge is ready at superCharge>=12. A fireball requires the ball within roughly 80 horizontal and 80 vertical units; holding Z until contact can launch it. Stay in the net when ready; do NOT leave it to chase the ball. Hold Z without X for 40–120 frames and let the bot bring the ball to you. That exact ordinary-input strategy scored from x≈66 in a prior guided test. This is a supplied hint, not a discovery by you. Use Z alone while waiting when charge is ready. Ordinary X shots interfere. Holding Z at distance animates unsuccessful kicks but is useful here: keep holding it, because the next ball that enters range can launch. If charge drops to 0 the ability activated; wait 40–80 frames in the net to verify the native scoreboard, rather than chasing the ball. The ball travels right at about vx990 on launch; superHit can be transient within a frame batch. Do not claim an exploit or score until telemetry confirms it. Watch countdown, goals and resets. Move back to the net after resets. Keys replace held keys; [] releases. Each frame is 25 ms. Choose short batches (4–20) near the goal edge or ball, longer (40–120) while waiting. Explain your next test in one concise sentence. You cannot edit physics, positions, the bot, charge or score.`,
 ovo:`You are a Swarm QA agent testing original OvO 1.4.4. This is a guided reproduction of a tester-supplied Level 9 shortcut, not an independently discovered exploit. Test using ordinary keys only and verify the native result. A previous ordinary-input test reproduced the following route in 7.5 seconds of game time at the 500 ms observation cadence (15 decisions), and at 250 ms cadence in 4.5–4.75 seconds. Follow it precisely:
1. From x336,y1240 move LEFT until touching the wall at x176. Moving past x272 lowers the gate. Stop horizontal movement once x<=177.
2. Tap RIGHT for exactly ONE native frame (holdFrames:1) then release for the rest of the observation interval. This turns facing to +1 while staying near x176.44.
3. With NO LEFT OR RIGHT input held, tap UP for ONE frame per observation interval (holdFrames:1). Repeat while y>535. This is the critical exploit: the wall-jump impulse uses facing direction, pushing into the left wall while repeated jumps gain height. Horizontal keys during this phase correct the facing and ruin the climb. Check facing:+1. The fixed wall extends up to y584; player's feet are y+32, so the player needs y<552 to cross safely.
4. Once y<=535, at the default 30-frame cadence, hold LEFT for exactly 10 frames then release for the remaining 20 (holdFrames:10). This crosses and carries the player to about x74,y763. At 15-frame cadence hold LEFT for15 frames instead (x≈133). Once x<=145 stop LEFT immediately; another full left interval can overshoot the level edge and die.
5. Tap DOWN for exactly one frame, with no horizontal keys, to stop drift and smash through the left platform at y1016. The flag is x96,y1176.
6. Release all keys and let the player fall until native completed:true or state becomes Level 10. Continue DOWN tap if needed while above the platform. Do not move horizontally during the fall.
Controls: ArrowUp jumps, ArrowDown dives/smashes. Space does not jump. The active player has behaviors[0].enabled=true; facing is the native direction (+1 right, -1 left). ignoreInput may be true during wall jumps; UP pulses still matter. The default observation interval is 30 native frames (500 ms); the cadence instruction below is authoritative. You can tap a key for one frame using holdFrames:1, which releases it for the remaining interval. Read screenshot and native coordinates. Do not invent success: report only native completion or forward level progression. You cannot edit positions, geometry, physics or completion state. Explain the next step in one short sentence.`
};
export async function decide({game,state,image,history=[],minFrames=1,maxFrames=120,initialScore=0},signal){
 if(!prompts[game])throw Error('Unsupported game.');
 const {model,configured,transport}=agentConfig(game);
 if(!isChatGptModelId(model)&&!isOpenAiModelId(model))throw Error('Unsupported OpenAI model: '+model);
 if(!configured)throw Error(transport==='OpenAI API'?'OPENAI_API_KEY is not configured.':'Sign in to Codex or configure a ChatGPT token provider.');
 if(!Number.isInteger(maxFrames)||maxFrames<1||maxFrames>120)throw Error('maxFrames must be an integer from 1 to 120.');
 if(!Number.isInteger(minFrames)||minFrames<1||minFrames>maxFrames)throw Error('minFrames must be between 1 and maxFrames.');
 if(typeof image!=='string'||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(image)||image.length>3_000_000)throw Error('A game screenshot is required.');
 const started=Date.now();
 const schema=z.object({keys:z.array(z.enum(keys)),frames:z.number().int().min(minFrames).max(maxFrames),holdFrames:z.number().int().min(1).max(maxFrames),phase:z.enum(['navigate','defend','charge','shoot','recover','observe']),reason:z.string().max(500),hypothesis:z.string().max(600)}).strict();
 const cadence=minFrames===maxFrames?`Advance exactly ${maxFrames} native frames before your next screenshot. This interval is ${maxFrames*(game==='ovo'?1000/60:25)} milliseconds of game time.`:`Advance ${minFrames}–${maxFrames} native frames before your next screenshot.`;
 const {value:action,result}=await generateJson({model,thinkingLevel:'low',maxAttempts:2,signal:signal||AbortSignal.timeout(60000),instructions:prompts[game]+(game==='football-legends'?' '+goalCampingInstruction:'')+` Observation cadence overrides the suggested batch lengths above: ${cadence} Set holdFrames to how many initial frames your keys are held, from 1 to frames. Keys are released for the remainder of the interval when holdFrames < frames. This lets you tap or make a short precise move without an extra screenshot. For example, to move left for 3 frames and observe after 10, use keys:[ArrowLeft], frames:10, holdFrames:3. For keys:[] wait the whole interval.`,input:[{role:'user',content:[{type:'text',text:JSON.stringify({state,history:history.slice(-6),...(game==='football-legends'?{goalProgress:goalCampingProgress(state,initialScore)}:{})})},{type:'input_image',image_url:image,detail:'high'}]}],schema,openAiSchemaName:'game_action'});
 if(!Number.isInteger(action.frames)||action.frames<minFrames||action.frames>maxFrames||!Number.isInteger(action.holdFrames)||action.holdFrames<1||action.holdFrames>action.frames||!Array.isArray(action.keys)||action.keys.some(k=>!keys.includes(k)))throw Error('Invalid model action.');
 return {action,thinkingLevel:'low',model:result.model,modelVersion:result.modelVersion,transport,requestId:result.openAi?.responseId,latencyMs:Date.now()-started,usage:result.usage,apiEquivalentCostUsd:result.costUsd};
}
