import assert from 'node:assert/strict';
import {explorationPolicy,profiles} from '../web/explore-policy.js';
import {createExploreDecider} from '../explore.mjs';
const state={state:'gameplay',core:{isPlaying:true},match:{score1:0,score2:0},players:[{human:true,x:300,y:336,onGround:true,superReady:true}],ball:{x:350,y:330,vx:100}};
const beginner=explorationPolicy({game:'football-legends',state,profile:'beginner'}),experienced=explorationPolicy({game:'football-legends',state,profile:'experienced'});
assert.equal(beginner.candidates.super,undefined);assert.equal(beginner.candidates.attack,undefined);
assert.deepEqual(experienced.candidates.super.action.keys,['KeyZ']);
assert.ok(beginner.candidates.move_right.action.holdFrames>experienced.candidates.move_right.action.holdFrames);
assert.throws(()=>explorationPolicy({game:'football-legends',state,profile:'invented'}),/Choose beginner or experienced/);
const stateCopy=structuredClone(state);let routeInput;
const decide=createExploreDecider({hasJev:()=>true,choose:async input=>{routeInput=input;return {choice:'kick',confidence:.94,model:'typesafe/jev-1.13',latencyMs:10};}});
const result=await decide({game:'football-legends',state,profile:'beginner'});
assert.equal(result.guided,false);assert.equal(result.purpose,'explore');assert.equal(result.profile,'beginner');assert.deepEqual(result.action.keys,['KeyX']);
assert.equal(routeInput.plan.goal,profiles.beginner.prompt);assert.equal('image' in routeInput,false);assert.deepEqual(state,stateCopy);
let reviewed=false;
const uncertain=createExploreDecider({hasJev:()=>true,choose:async()=>({choice:'kick',confidence:.4,model:'typesafe/jev-1.13'}),review:async input=>{reviewed=true;assert.equal(input.profile,'experienced');return {choice:'super',reason:'Charged ball in range',model:'visual'};}});
assert.equal((await uncertain({game:'football-legends',state,profile:'experienced'})).needsVisual,true);assert.equal(reviewed,false);
const review=await uncertain({game:'football-legends',state,profile:'experienced',image:'test fixture'});assert.equal(review.visualReview,true);assert.equal(review.guided,false);assert.deepEqual(review.action.keys,['KeyZ']);
const invalid=createExploreDecider({hasJev:()=>true,choose:async()=>({choice:'super',confidence:1})});
await assert.rejects(invalid({game:'football-legends',state,profile:'beginner'}),/unavailable action/);
const cancellation=new AbortController();cancellation.abort();await assert.rejects(decide({game:'football-legends',state,profile:'beginner'},cancellation.signal),{name:'AbortError'});
const noJev=createExploreDecider({hasJev:()=>false});assert.equal((await noJev({game:'football-legends',state,profile:'beginner'})).needsVisual,true);
const paused=createExploreDecider({hasJev:()=>{throw Error('Native transitions need no provider.');}});
const transition=await paused({game:'football-legends',state:{...state,core:{isCountDown:true}},profile:'beginner'});
assert.equal(transition.engineWait,true);assert.equal(transition.model,'Native transition');assert.deepEqual(transition.action.keys,[]);assert.equal(transition.latencyMs,0);
const platformState={state:'Level 2',completed:false,players:[{x:270,y:352,width:32,height:64,facing:1,behaviors:[{enabled:true,wasOnFloor:true,dx:330,dy:0,maxspeed:330,acc:1500,dec:1500}]}],objects:[{type:'t51',bounds:{left:32,right:320,top:384,bottom:393}},{type:'t51',bounds:{left:448,right:608,top:384,bottom:393}},{type:'t44',x:2264,y:440}]};
const noviceGap=explorationPolicy({game:'ovo',state:platformState,profile:'beginner'}),expertGap=explorationPolicy({game:'ovo',state:platformState,profile:'experienced'});
assert.equal(noviceGap.features.gapAhead,false,'A first-time player does not receive the distant gap forecast.');
assert.equal(expertGap.features.needsApproach,true);assert.deepEqual(expertGap.candidates.approach_edge.action.keys,[],'Brake before a running jump would start too early.');
assert.equal(noviceGap.candidates.wall_jump,undefined);assert.ok(expertGap.candidates.wall_jump);
assert.ok(expertGap.candidates.jump_right.action.holdFrames<30,'The experienced jump releases Up before the next decision to allow ordinary wall jumps.');
const breakable={...platformState,players:[{...platformState.players[0],x:1470,y:192}],objects:[{type:'t45',bounds:{left:1432,right:1528,top:224,bottom:232}},{type:'t44',x:2264,y:440}]};
const expertSmash=explorationPolicy({game:'ovo',state:breakable,profile:'experienced'});
assert.equal(expertSmash.features.terrain,'smashable_platform');assert.deepEqual(expertSmash.candidates.prepare_smash.action.keys,['ArrowUp']);
assert.deepEqual(expertSmash.candidates.smash.action.keys,['ArrowDown']);assert.equal(explorationPolicy({game:'ovo',state:breakable,profile:'beginner'}).candidates.smash,undefined);
console.log('Explore: profile boundaries, control precision, routine movement, visual escalation, cancellation and ordinary-play provenance verified.');
