import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {browser} from './browser.mjs';
import {captureGame,verifyQuarterSecondAction,verifyHalfSecondAction} from './verify-helpers.mjs';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const hash=b=>createHash('sha256').update(b).digest('hex');
const active=s=>s.players.find(p=>p.behaviors[0]?.enabled&&!p.behaviors[0]?.ignoreInput);
const b=await browser();try{
 const p=await b.newPage({viewport:{width:1280,height:1040}});
 const errors=[],external=[],failed=[];
 p.on('pageerror',e=>errors.push(e.message));
 p.on('request',r=>{if(!/^(localhost|127\.0\.0\.1)$/.test(new URL(r.url()).hostname))external.push(r.url());});
 p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))failed.push({url:r.url(),status:r.status()});});
 await p.goto('http://localhost:4173/ovo');
 await p.waitForFunction(()=>window.gameAgent?.observe().ready,{},{timeout:15000});
 await p.evaluate(()=>gameAgent.startLevel(1));
 await p.evaluate(()=>gameAgent.step({frames:100,keys:[]}));
 await mkdir('evidence',{recursive:true});await mkdir('private/previews',{recursive:true});
 const before=await p.evaluate(()=>gameAgent.observe());
 const pixels=(await captureGame(p,{path:'evidence/ovo-frozen-before.png'})).bytes;
 await sleep(4000);
 assert.deepEqual(await p.evaluate(()=>gameAgent.observe()),before,'All OvO state must stay frozen while the agent thinks.');
 const after=(await captureGame(p,{path:'evidence/ovo-frozen-after.png'})).bytes;
 assert.equal(hash(after),hash(pixels),'OvO pixels must stay identical.');
 const one=await p.evaluate(()=>gameAgent.step({frames:1,keys:[]}));
 assert.equal(one.engineTicks,before.engineTicks+1);
 assert.equal(one.clock.frames,before.clock.frames+1);
 assert.ok(Math.abs(one.engineSeconds-before.engineSeconds-1/60)<1e-8);
 assert.ok(Math.abs(one.dt-1/60)<1e-8);
 const cadence=await verifyQuarterSecondAction(p,'ovo');
 const defaultCadence=await verifyHalfSecondAction(p,'ovo');
 const moved=await p.evaluate(()=>gameAgent.step({frames:12,keys:['ArrowRight']}));
 assert.ok(active(moved).x-active(defaultCadence.after).x>10,'Right input must move the active player.');
 const jump=await p.evaluate(()=>gameAgent.step({frames:8,keys:['ArrowUp']}));
 assert.ok(active(jump).y<active(moved).y-10,'Up input must jump.');
 await p.evaluate(()=>gameAgent.releaseKeys());
 const frame=p.frames().find(f=>f.url().includes('/game/ovo/index.html'));
 await frame.evaluate(()=>{window.__timer=0;setTimeout(()=>window.__timer++,100);});
 await sleep(200);assert.equal(await frame.evaluate(()=>window.__timer),0);
 await p.evaluate(()=>gameAgent.step({frames:7,keys:[]}));assert.equal(await frame.evaluate(()=>window.__timer),1);
 const previewBefore=await p.evaluate(()=>gameAgent.observe());await p.locator('#preview').click();await sleep(1100);
 const previewAfter=await p.evaluate(()=>gameAgent.observe());
 const previewFrames=previewAfter.clock.frames-previewBefore.clock.frames;
 assert.ok(previewFrames>=3&&previewFrames<=5);
 const takeover=await p.evaluate(()=>gameAgent.step({frames:1}));await sleep(350);assert.deepEqual(await p.evaluate(()=>gameAgent.observe()),takeover);
 assert.equal(await p.locator('#preview').getAttribute('aria-pressed'),'false');
 await p.evaluate(()=>gameAgent.startLevel(9));await p.evaluate(()=>gameAgent.step({frames:60,keys:[]}));
 const level9=await p.evaluate(()=>gameAgent.observe());assert.equal(level9.state,'Level 9');assert.ok(active(level9));
 await captureGame(p,{path:'private/previews/ovo.png'});await p.screenshot({path:'evidence/ovo-demo.png',fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(failed,[]);
 const checks={...defaultCadence.checks,quarterSecondCapability:cadence.checks,frozenStateUnchanged:true,pixelsIdentical:true,singleFrameEngineSeconds:one.engineSeconds-before.engineSeconds,singleFrameEngineTicks:one.engineTicks-before.engineTicks,rightMovement:active(moved).x-active(defaultCadence.after).x,jumpHeight:active(moved).y-active(jump).y,timersUseSyntheticTime:true,previewFramesIn1100ms:previewFrames,agentStopsPreview:true,level9Loads:true,external,errors,failed};
 await writeFile('evidence/ovo-verification.json',JSON.stringify({verifiedAt:new Date().toISOString(),checks,before,one,level9},null,2));console.log(JSON.stringify(checks,null,2));
}finally{await b.close();}
